services:
  db:
    image: postgres:16-alpine
    container_name: abfab-db
    environment:
      POSTGRES_DB: aBetForABeer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aBetForABeer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
