CREATE TABLE IF NOT EXISTS bets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  user_id  BIGINT NOT NULL REFERENCES users(id)   ON DELETE CASCADE,
  predicted_home_goals INTEGER NOT NULL CHECK (predicted_home_goals >= 0),
  predicted_away_goals INTEGER NOT NULL CHECK (predicted_away_goals >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_bet_user_match UNIQUE (user_id, match_id)
);

CREATE INDEX IF NOT EXISTS idx_bets_match ON bets(match_id);
CREATE INDEX IF NOT EXISTS idx_bets_user  ON bets(user_id);
